#!/bin/bash
uname=`whoami`
	echo "Now input the password of $uname"
	read upass
	passcheck=`echo "$upass" | sudo -S echo "i love amber forever"`
	if [ "$passcheck" != "i love amber forever" ];then
	echo "E:Wrong Password"
	exit 1	
	else 
	echo "go go Baron Bunny"	
	fi
