#!/bin/bash
uname=`whoami`
	echo "Now input the password of $uname"
	read upass
	passcheck=`echo "$upass" | sudo -S echo "i love amber forever"`
	passcheck=`echo "$upass" | sudo -S echo "i love amber forever"`
	reset
	###UOS魔改的sudo返回了验证成功干扰判断，会变成验证成功i love amber forever
	### 听我说谢谢你，因为有你，温暖了四季
	###fuck♂you 就不能改的不那么坑爹吗？？？还是我用来捕捉的方法太笨了。。。
	if [ "$passcheck" != "i love amber forever" ];then
	echo "114514首"
	exit 1	
	else
	reset 
	echo "go go Baron Bunny"	
	fi
