version: '1.0'
name: dtk-build-release-tag-20220425
displayName: dtk-build-release-tag
triggers:
  trigger: auto
  push:
    tags:
      prefix:
        - ''
stages:
  - name: stage-4e566164
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的DTK构建
        certificate: ''
        image: docker.io/debian:buster
        command:
          - sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
          - '# 换源'
          - apt update
          - export DEBIAN_FRONTEND=noninteractive
          - echo "安装git devscripts equivs curl..."
          - 'apt install git devscripts equivs curl -y '
          - git clone https://gitlink.org.cn/shenmo7192/dtk-old-bundle.git
          - cd dtk-old-bundle
          - apt install ./*.deb -y
          - cd ..
          - rm -rf dtk-old-bundle
          - ''
          - 'mk-build-deps --install --tool "apt-get -o Debug::pkgProblemResolver=yes  -y" '
          - ''
          - dpkg-buildpackage -b -us -uc
          - cd ..
          - ls -all
          - pwd
          - ''
          - 'mkdir target '
          - for f in $(find . -type f -name "*.deb")
          - do
          - '    mv $f target'
          - done
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ../target
        notify: []
        strategy:
          retry: '0'
  - name: stage-29f3ffbb
    displayName: 上传
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify: []
        strategy:
          retry: '0'
