#!/bin/sh


if [ "$1" = "triggered" ]; then
	if [ -f "/usr/bin/deepin-app-store-tool" ]; then 
	exit 0
	fi
  echo '--------检测到Uniontech标准软件包，运行补丁以修正安装--------'
    /usr/local/bin/spark-dstore-patch
  echo '-----------spark-dstore-patch补丁工具已运行完毕-----------'
else

mkdir -p /usr/local/bin

ln -s -f /opt/durapps/spark-store/bin/spark-store /usr/local/bin/spark-store
ln -s -f /opt/durapps/spark-store/bin/ssinstall /usr/local/bin/ssinstall
ln -s -f /opt/durapps/spark-store/bin/spark-dstore-patch /usr/local/bin/spark-dstore-patch

cd /tmp/spark-store-install
wget https://d.store.deepinos.org.cn/dcs-repo.gpg-key.asc
apt-key add dcs-repo.gpg-key.asc
# wget https://d.store.deepinos.org.cn/ssrepokey.asc
# apt-key add ssrepokey.asc


update-icon-caches /usr/share/icons/hicolor || true
update-desktop-database /usr/share/applications || true
xdg-mime default spark-store.desktop x-scheme-handler/spk
update-mime-database /usr/share/mime || true

exit 0
fi
exit 0
# /tmp/spark-store-install/feedback.sh
